INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Quiver of Alacrity','QUIVER',1);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Epic Quiver of Alacrity','QUIVER',20);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Quiver of Poison (ML 12)','QUIVER',12);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Quiver of Poison (ML 13)','QUIVER',13);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Quiver of Poison (ML 14)','QUIVER',14);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Quiver of Poison (ML 23)','QUIVER',23);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Quiver of Poison (ML 24)','QUIVER',24);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Quiver of Poison (ML 25)','QUIVER',25);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Quivering Quiver','QUIVER',1);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Dynamistic Quiver','QUIVER',14);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Epic Dynamistic Quiver','QUIVER',14);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Purifying Quiver','QUIVER',10);
INSERT INTO ITEM (NAME,SLOT,ML) VALUES ('Epic Purifying Quiver','QUIVER',29);

INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Quiver of Alacrity','Ranged Alacrity','Enhancement',10);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Quiver of Alacrity','Striding','Enhancement',30);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Quiver of Alacrity','Striding','Enhancement',30);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Epic Quiver of Alacrity','Concentration','Penality',-50);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Epic Quiver of Alacrity','Striding','Enhancement',30);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Epic Quiver of Alacrity','Ranged Alacrity','Enhancement',15);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Epic Quiver of Alacrity','Distant Diversion','Insightful',15);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Epic Quiver of Alacrity','Deception','Insightful',4);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Epic Quiver of Alacrity','Doubleshot','Enhancement',8);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Quiver of Poison (ML 12)','Venomed Ammunition','Venom',2);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Quiver of Poison (ML 13)','Venomed Ammunition','Venom',3);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Quiver of Poison (ML 14)','Venomed Ammunition','Venom',4);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Quiver of Poison (ML 23)','Venomed Ammunition','Venom',6);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Quiver of Poison (ML 24)','Venomed Ammunition','Venom',8);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Quiver of Poison (ML 25)','Venomed Ammunition','Venom',10);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Quivering Quiver','Arrow Spitting',NULL,NULL);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Dynamistic Quiver','Doubleshot','Enhancement',5);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Dynamistic Quiver','Ranged Power','Enhancement',2);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Epic Dynamistic Quiver','Doubleshot','Enhancement',8);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Epic Dynamistic Quiver','Ranged Power','Enhancement',4);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Purifying Quiver','Burning Ammunition','Fire',2);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Epic Purifying Quiver','Burning Ammunition','Fire',8);
INSERT INTO ITEM_EFFECTS (ID,ITEM_NAME,EFFECT,EFFECT_TYPE,EFFECT_VALUE) VALUES (item_effects_sequence.nextval,'Epic Purifying Quiver','Blunted Ammunition','blunt',NULL);
