insert into item_skippable (name) values ('The Changestone');
insert into item_skippable (name) values ('Enchanted Chocolates by Fabiano & Zelda');
insert into item_skippable (name) values ('Seal of House Avithoul');
insert into item_skippable (name) values ('Seal of House Dun''Robar');
insert into item_skippable (name) values ('Seal of House Szind');
insert into item_skippable (name) values ('Planar Focus of Subterfuge');
insert into item_skippable (name) values ('Planar Focus of Prowess');
insert into item_skippable (name) values ('Planar Focus of Erudition');
insert into item_skippable (name) values ('Spider-spun Caparison');
insert into item_skippable (name) values ('Star of Day');
insert into item_skippable (name) values ('Spidersilk Robes');
insert into item_skippable (name) values ('Hide of the Goristro');
insert into item_skippable (name) values ('Terrorweb Chitin Breastplate');
insert into item_skippable (name) values ('Embrace of the Spider Queen');
insert into item_skippable (name) values ('Helm of the Black Dragon');
insert into item_skippable (name) values ('Helm of the White Dragon');
insert into item_skippable (name) values ('Helm of the Blue Dragon');
insert into item_skippable (name) values ('Intricate Field Optics');
insert into item_skippable (name) values ('Skullduggery Kit');
insert into item_skippable (name) values ('Prisoner''s Manacles');
insert into item_skippable (name) values ('Shade''s Hood');
insert into item_skippable (name) values ('Stolen Necklace');
insert into item_skippable (name) values ('Prison Break');
insert into item_skippable (name) values ('Fell Shiv');
insert into item_skippable (name) values ('Goatskin Boots');
insert into item_skippable (name) values ('Prismatic Cloak');
insert into item_skippable (name) values ('Master''s Riposte');
insert into item_skippable (name) values ('Magistrate''s Scepter');
insert into item_skippable (name) values ('Elemental Fury');
insert into item_skippable (name) values ('Shadowmail');
insert into item_skippable (name) values ('Tainted Helm of Mystery');
insert into item_skippable (name) values ('Mysterious Ring');
insert into item_skippable (name) values ('Collective Sight');
insert into item_skippable (name) values ('Dream Edge');
insert into item_skippable (name) values ('Rahl''s Might');
insert into item_skippable (name) values ('Chimera''s Fang');
insert into item_skippable (name) values ('Belashyrra''s Cleansed Scepter');

--insert into item_skippable (name) values ('');