insert into effect(name, effect_type) values ('Alarphon''s Staff: Spell Selection', 'clickie');
insert into effect(name, effect_type) values ('Acid Breath', 'clickie');
insert into effect(name, effect_type) values ('Aid', 'clickie');
insert into effect(name, effect_type) values ('Bestow Curse', 'clickie');
insert into effect(name, effect_type) values ('Bless', 'clickie');
insert into effect(name, effect_type) values ('Blinding Flash', 'clickie');
insert into effect(name, effect_type) values ('Blood Sacrifice', 'clickie');
insert into effect(name, effect_type) values ('Blur', 'clickie');
insert into effect(name, effect_type) values ('Break Enchantment', 'clickie');
insert into effect(name, effect_type) values ('Burning Hands', 'clickie');
insert into effect(name, effect_type) values ('Call Lightning Storm', 'clickie');
insert into effect(name, effect_type) values ('Camouflage', 'clickie');
insert into effect(name, effect_type) values ('Cause Fear', 'clickie');
insert into effect(name, effect_type) values ('Chain Lightning', 'clickie');
insert into effect(name, effect_type) values ('Charm Canine', 'clickie');
insert into effect(name, effect_type) values ('Charm Person', 'clickie');
insert into effect(name, effect_type) values ('Cloudkill', 'clickie');
insert into effect(name, effect_type) values ('Cone of Cold', 'clickie');
insert into effect(name, effect_type) values ('Command Undead', 'clickie');
insert into effect(name, effect_type) values ('Control Undead', 'clickie');
insert into effect(name, effect_type) values ('Crushing Despair', 'clickie');
insert into effect(name, effect_type) values ('Cure Critical Wounds, Mass', 'clickie');
insert into effect(name, effect_type) values ('Cure Light Wounds', 'clickie');
insert into effect(name, effect_type) values ('Cure Serious Wounds', 'clickie');
insert into effect(name, effect_type) values ('Cure Serious Wounds, Mass', 'clickie');
insert into effect(name, effect_type) values ('Cyclonic Blast', 'clickie');
insert into effect(name, effect_type) values ('Dark Discorporation', 'clickie');
insert into effect(name, effect_type) values ('Death Ward', 'clickie');
insert into effect(name, effect_type) values ('Death Ward, Mass', 'clickie');
insert into effect(name, effect_type) values ('Deep Slumber', 'clickie');
insert into effect(name, effect_type) values ('Detect Secret Doors', 'clickie');
insert into effect(name, effect_type) values ('Dimension Door', 'clickie');
insert into effect(name, effect_type) values ('Disintegrate', 'clickie');
insert into effect(name, effect_type) values ('Dismissal', 'clickie');
insert into effect(name, effect_type) values ('Dispel Madstone Effects', 'clickie');
insert into effect(name, effect_type) values ('Dispel the Grip of Strahd', 'clickie');
insert into effect(name, effect_type) values ('Displacement', 'clickie');
insert into effect(name, effect_type) values ('Doom', 'clickie');
insert into effect(name, effect_type) values ('Expeditious Retreat', 'clickie');
insert into effect(name, effect_type) values ('Fear', 'clickie');
insert into effect(name, effect_type) values ('Feather Fall', 'clickie');
insert into effect(name, effect_type) values ('Fire Shield (fire version)', 'clickie');
insert into effect(name, effect_type) values ('Fire Storm', 'clickie');
insert into effect(name, effect_type) values ('Fireball', 'clickie');
insert into effect(name, effect_type) values ('Flame Strike', 'clickie');
insert into effect(name, effect_type) values ('Flaming Sphere', 'clickie');
insert into effect(name, effect_type) values ('Frost Lance', 'clickie');
insert into effect(name, effect_type) values ('Good Hope', 'clickie');
insert into effect(name, effect_type) values ('Gorgon Breath', 'clickie');
insert into effect(name, effect_type) values ('Greater Command', 'clickie');
insert into effect(name, effect_type) values ('Greater Ardor', 'clickie');
insert into effect(name, effect_type) values ('Greater Efficacy', 'clickie');
insert into effect(name, effect_type) values ('Greater Erosion', 'clickie');
insert into effect(name, effect_type) values ('Greater Freeze', 'clickie');
insert into effect(name, effect_type) values ('Greater Inferno', 'clickie');
insert into effect(name, effect_type) values ('Greater Spark', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('Greater Restoration', 'clickie');
insert into effect(name, effect_type) values ('Greater Teleport', 'clickie');
insert into effect(name, effect_type) values ('Harm', 'clickie');
insert into effect(name, effect_type) values ('Haste', 'clickie');
insert into effect(name, effect_type) values ('Heal', 'clickie');
insert into effect(name, effect_type) values ('Heal Light Wounds', 'clickie');
insert into effect(name, effect_type) values ('Heal Moderate Wounds', 'clickie');
insert into effect(name, effect_type) values ('Heal, Mass', 'clickie');
insert into effect(name, effect_type) values ('Hold Person', 'clickie');
insert into effect(name, effect_type) values ('Hold Person, Mass', 'clickie');
insert into effect(name, effect_type) values ('Horn of Thunder', 'clickie');
insert into effect(name, effect_type) values ('Howl of Terror', 'clickie');
insert into effect(name, effect_type) values ('Hypnotic Pattern', 'clickie');
insert into effect(name, effect_type) values ('Longstrider', 'clickie');
insert into effect(name, effect_type) values ('Madstone Rage', 'clickie');
insert into effect(name, effect_type) values ('Mage Armor', 'clickie');
insert into effect(name, effect_type) values ('Major Mnemonic Aid', 'clickie');
insert into effect(name, effect_type) values ('Major Mnemonic Enhancer', 'clickie');
insert into effect(name, effect_type) values ('Melf''s Acid Arrow', 'clickie');
insert into effect(name, effect_type) values ('Meteor Swarm', 'clickie');
insert into effect(name, effect_type) values ('Move like the Night', 'clickie');
insert into effect(name, effect_type) values ('Nightshield', 'clickie');
insert into effect(name, effect_type) values ('Order''s Wrath', 'clickie');
insert into effect(name, effect_type) values ('Otto''s Irresistible Dance', 'clickie');
insert into effect(name, effect_type) values ('Otto''s Resistible Dance', 'clickie');
insert into effect(name, effect_type) values ('Panacea', 'clickie');
insert into effect(name, effect_type) values ('Prismatic Spray', 'clickie');
insert into effect(name, effect_type) values ('Protection from Elements, Mass', 'clickie');
insert into effect(name, effect_type) values ('Purple Faerie Fire', 'clickie');
insert into effect(name, effect_type) values ('Rage', 'clickie');
insert into effect(name, effect_type) values ('Raise Dead', 'clickie');
insert into effect(name, effect_type) values ('Reconstruct', 'clickie');
insert into effect(name, effect_type) values ('Repair Light Damage', 'clickie');
insert into effect(name, effect_type) values ('Repair Moderate Damage', 'clickie');
insert into effect(name, effect_type) values ('Resist Energy: Fire', 'clickie');
insert into effect(name, effect_type) values ('Restoration', 'clickie');
insert into effect(name, effect_type) values ('Roc''s Strength', 'clickie');
insert into effect(name, effect_type) values ('Scare', 'clickie');
insert into effect(name, effect_type) values ('Shield', 'clickie');
insert into effect(name, effect_type) values ('Shield of Faith', 'clickie');
insert into effect(name, effect_type) values ('Shout', 'clickie');
insert into effect(name, effect_type) values ('Sleep', 'clickie');
insert into effect(name, effect_type) values ('Slow', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');

--insert into effect(name, effect_type) values ('', 'clickie');