insert into item_skippable (name) values ('The Changestone');
insert into item_skippable (name) values ('Enchanted Chocolates by Fabiano & Zelda');
insert into item_skippable (name) values ('Seal of House Avithoul');
insert into item_skippable (name) values ('Seal of House Dun''Robar');
insert into item_skippable (name) values ('Seal of House Szind');
insert into item_skippable (name) values ('Planar Focus of Subterfuge');
insert into item_skippable (name) values ('Planar Focus of Prowess');
insert into item_skippable (name) values ('Planar Focus of Erudition');
insert into item_skippable (name) values ('Spider-spun Caparison');
insert into item_skippable (name) values ('Star of Day');
insert into item_skippable (name) values ('Spidersilk Robes');
insert into item_skippable (name) values ('Hide of the Goristro');
insert into item_skippable (name) values ('Terrorweb Chitin Breastplate');
insert into item_skippable (name) values ('Embrace of the Spider Queen');
insert into item_skippable (name) values ('Helm of the Black Dragon');
insert into item_skippable (name) values ('Helm of the White Dragon');
insert into item_skippable (name) values ('Helm of the Blue Dragon');
insert into item_skippable (name) values ('Intricate Field Optics');
insert into item_skippable (name) values ('Skullduggery Kit');
insert into item_skippable (name) values ('Prisoner''s Manacles');
insert into item_skippable (name) values ('Shade''s Hood');
insert into item_skippable (name) values ('Stolen Necklace');
insert into item_skippable (name) values ('Prison Break');
insert into item_skippable (name) values ('Fell Shiv (Level 25)');
insert into item_skippable (name) values ('Fell Shiv (Level 26)');
insert into item_skippable (name) values ('Fell Shiv (Level 27)');
insert into item_skippable (name) values ('Goatskin Boots');
insert into item_skippable (name) values ('Prismatic Cloak');
insert into item_skippable (name) values ('Master''s Riposte');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 17)');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 18)');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 19)');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 26)');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 27)');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 28)');
insert into item_skippable (name) values ('Elemental Fury');
insert into item_skippable (name) values ('Shadowmail (Level 16)');
insert into item_skippable (name) values ('Shadowmail (Level 17)');
insert into item_skippable (name) values ('Shadowmail (Level 18)');
insert into item_skippable (name) values ('Shadowmail (Level 23)');
insert into item_skippable (name) values ('Shadowmail (Level 24)');
insert into item_skippable (name) values ('Shadowmail (Level 25)');
insert into item_skippable (name) values ('Tainted Helm of Mystery');
insert into item_skippable (name) values ('Mysterious Ring');
insert into item_skippable (name) values ('Collective Sight');
insert into item_skippable (name) values ('Dream Edge');
insert into item_skippable (name) values ('Rahl''s Might');
insert into item_skippable (name) values ('Chimera''s Fang');
insert into item_skippable (name) values ('Belashyrra''s Cleansed Scepter');
insert into item_skippable (name) values ('Kindred Spirit');
insert into item_skippable (name) values ('Legendary Kindred Spirit');
insert into item_skippable (name) values ('Alpha Phase Goggles');
insert into item_skippable (name) values ('Beta Phase Goggles');
insert into item_skippable (name) values ('-1 Quarterstaff of Lesser Halfling Bane');
insert into item_skippable (name) values ('Rose Colored Goggles');
insert into item_skippable (name) values ('Steps'' Lenses of Seein'' Hidden Hand Secrets');
insert into item_skippable (name) values ('Dull Dagger');
insert into item_skippable (name) values ('Battleworn Chainshirt');
insert into item_skippable (name) values ('Battleworn Breastplate');
insert into item_skippable (name) values ('Battleworn Chainmail');
insert into item_skippable (name) values ('Ember Sickle');
insert into item_skippable (name) values ('Ember Heavy Mace');
insert into item_skippable (name) values ('Ember Great Axe');
insert into item_skippable (name) values ('Ember Longsword');
insert into item_skippable (name) values ('Ember Longbow');
insert into item_skippable (name) values ('Ember Rapier');
insert into item_skippable (name) values ('Ember Shortbow');
insert into item_skippable (name) values ('Toothpick');
insert into item_skippable (name) values ('Eye of Vol');
insert into item_skippable (name) values ('Urthullz Petrified Stalk');
insert into item_skippable (name) values ('Cold Fire');
insert into item_skippable (name) values ('Golem Gem');
insert into item_skippable (name) values ('Festival Luck Charms');
insert into item_skippable (name) values ('');
insert into item_skippable (name) values ('');
insert into item_skippable (name) values ('');
insert into item_skippable (name) values ('');
insert into item_skippable (name) values ('');
insert into item_skippable (name) values ('');
insert into item_skippable (name) values ('');

--insert into item_skippable (name) values ('');