insert into effect(name, effect_type) values ('Armor Bonus', 'defense');
insert into effect(name, effect_type) values ('Armor Mastery', 'defense');
insert into effect(name, effect_type) values ('Fortification', 'defense');
insert into effect(name, effect_type) values ('Physical Sheltering', 'defense');
insert into effect(name, effect_type) values ('Magical Sheltering', 'defense');
insert into effect(name, effect_type) values ('Magical Sheltering Cap', 'defense');
insert into effect(name, effect_type, description) values ('DR', 'defense', 'Damage Reduction');
insert into effect(name, effect_type) values ('Dodge', 'defense');
insert into effect(name, effect_type) values ('Concealment', 'defense');
insert into effect(name, effect_type) values ('Incorporeal', 'defense');
insert into effect(name, effect_type) values ('Spell Resistance', 'defense');

-- Special defense
insert into effect(name, effect_type, description) values ('Chaos Guard', 'defense', 'The bearer of this item gains +2 Deflection bonus to AC and +2 Resistance bonus to saving throws from Chaotic Enemies.');
insert into effect(name, effect_type, description) values ('Protection from Evil', 'defense', 'The bearer of this item gains +2 Deflection bonus to AC and +2 Resistance bonus to saving throws from Chaotic Enemies.');
insert into effect(name, effect_type) values ('Druidic Stoneshape', 'defense');
insert into effect(name, effect_type) values ('Druidic Survival Mastery', 'defense');
--insert into effect(name, effect_type) values ('', '');

-- Special Guards
insert into effect(name, effect_type) values ('Air Guard', 'guard');
insert into effect(name, effect_type) values ('Cacophonic Guard', 'guard');
insert into effect(name, effect_type) values ('Crushing Wave Guard', 'guard');
insert into effect(name, effect_type, description) values ('Demonic Curse', 'guard', 'Each time you are hit in melee combat there is a chance that your attacker will be Cursed.');
insert into effect(name, effect_type, description) values ('Legendary Demonic Curse', 'guard', 'Each time you are hit in melee combat there is a chance that your attacker will be Cursed.');
insert into effect(name, effect_type, description) values ('Demonic Retribution', 'guard', 'Each time you are hit in melee combat there is a chance that a demonic force will strike back at your attacker hitting them with an Inflict Moderate Wounds spell.');
insert into effect(name, effect_type) values ('Disease Guard', 'guard');
insert into effect(name, effect_type) values ('Disintegration Guard', 'guard');
insert into effect(name, effect_type) values ('Earthgrab Guard', 'guard');
insert into effect(name, effect_type) values ('Epic Transmuted Platinum Guard', 'guard');
insert into effect(name, effect_type) values ('Fearsome', 'guard');
insert into effect(name, effect_type) values ('Freezing Ice Guard', 'guard');
insert into effect(name, effect_type) values ('From The Shadows', 'guard');
insert into effect(name, effect_type) values ('Greater Disease Guard', 'guard');
insert into effect(name, effect_type) values ('Greater Dispelling Guard', 'guard');
insert into effect(name, effect_type) values ('Greater Disruption Guard', 'guard');
insert into effect(name, effect_type) values ('Greater Poison Guard', 'guard');
insert into effect(name, effect_type) values ('Haste Guard', 'guard');
insert into effect(name, effect_type) values ('Improved Disease Guard', 'guard');
insert into effect(name, effect_type) values ('Magma Surge Guard', 'guard');
insert into effect(name, effect_type) values ('Lesser Undead Guard', 'guard');
insert into effect(name, effect_type) values ('Undead Guard', 'guard');
insert into effect(name, effect_type) values ('Fire Shield (Cold) Miss-Guard', 'guard');
insert into effect(name, effect_type) values ('Invisibility Guard', 'guard');
insert into effect(name, effect_type) values ('Lesser Stone Prison Guard', 'guard');
insert into effect(name, effect_type) values ('Legendary Lightningstorm Guard', 'guard');
insert into effect(name, effect_type) values ('Lightningstorm Guard', 'guard');
insert into effect(name, effect_type) values ('Nightmare Guard', 'guard');
insert into effect(name, effect_type) values ('Sticky Goo Guard', 'guard');
insert into effect(name, effect_type) values ('Transmuted Platinum Guard', 'guard');
insert into effect(name, effect_type) values ('Legendary Magma Surge Guard', 'guard');
insert into effect(name, effect_type) values ('Legendary Nightmare Guard', 'guard');
insert into effect(name, effect_type) values ('Nullmagic Guard', 'guard');
insert into effect(name, effect_type) values ('Radiance Guard', 'guard');
insert into effect(name, effect_type) values ('Legendary Ice Shards Guard', 'guard');
insert into effect(name, effect_type) values ('Trap the Soul Guard', 'guard');
insert into effect(name, effect_type) values ('Legendary Brilliance Guard', 'guard');
insert into effect(name, effect_type) values ('Legendary Cacophonic Guard', 'guard');
insert into effect(name, effect_type) values ('Roar', 'guard');
insert into effect(name, effect_type, description) values ('Vengeful Fury', 'guard', 'On Taking Damage: Gain a 12% Enhancement Bonus to Doublestrike and a +4 Rage Bonus to your Attack Bonus.');
insert into effect(name, effect_type, description) values ('Spike Guard', 'guard', 'On Being Hit in Melee: 5% chance to do 510 to 700 Piercing Damage to the Attacker.');
insert into effect(name, effect_type) values ('Utter Disintegration Guard', 'guard');
insert into effect(name, effect_type) values ('Lightning Storm Guard', 'guard');
insert into effect(name, effect_type) values ('Legendary Stone Guard', 'guard');
insert into effect(name, effect_type) values ('Light of Dawn', 'guard');
insert into effect(name, effect_type) values ('Legendary Disease Guard', 'guard');
insert into effect(name, effect_type) values ('Incineration Guard', 'guard');
insert into effect(name, effect_type) values ('Superior Undead Guard', 'guard');
insert into effect(name, effect_type) values ('Legendary Air Guard', 'guard');
insert into effect(name, effect_type) values ('Telekinesis Guard', 'guard');
insert into effect(name, effect_type) values ('Legendary Earthgrab Guard', 'guard');
--insert into effect(name, effect_type) values ('', 'guard');

-- Plain Damage guards
insert into effect(name, effect_type) values ('Acid Guard', 'guard');
insert into effect(name, effect_type) values ('Lightning Guard', 'guard');
insert into effect(name, effect_type) values ('Fire Guard', 'guard');
insert into effect(name, effect_type) values ('Ice Guard', 'guard');
insert into effect(name, effect_type) values ('Sonic Guard', 'guard');
insert into effect(name, effect_type) values ('Light Guard', 'guard');
insert into effect(name, effect_type) values ('Evil Guard', 'guard');
insert into effect(name, effect_type) values ('Good Guard', 'guard');
insert into effect(name, effect_type) values ('Negative Guard', 'guard');
insert into effect(name, effect_type) values ('Poison Guard', 'guard');
insert into effect(name, effect_type) values ('Damage Guard', 'guard');
insert into effect(name, effect_type) values ('Thorn Guard', 'guard');
insert into effect(name, effect_type) values ('Greater Thorn Guard', 'guard');
-- On-Hit buffs
insert into effect(name, effect_type) values ('Angelic Grace', 'guard');
insert into effect(name, effect_type) values ('Healers Bounty', 'guard');
insert into effect(name, effect_type) values ('Ice Barrier', 'guard');
insert into effect(name, effect_type) values ('Legendary Ice Barrier', 'guard');
insert into effect(name, effect_type, description) values ('Demonic Shield', 'guard', 'Each time you are hit in melee combat there is a chance that a shield of demonic energy will grant you a +30 Profane bonus to temporary hit points.');
insert into effect(name, effect_type, description) values ('Improved Demonic Shield', 'guard', 'Each time you are hit in melee combat there is a chance that a shield of demonic energy will grant you a +30 Profane bonus to temporary hit points.');
insert into effect(name, effect_type, description) values ('Legendary Demonic Shield', 'guard', 'Each time you are hit in melee combat there is a chance that a shield of demonic energy will grant you a +30 Profane bonus to temporary hit points.');
insert into effect(name, effect_type, description) values ('Earthen Guard', 'guard', 'When you are successfully attacked, there is a chance that a Stone Skin will be cast on you.');
insert into effect(name, effect_type, description) values ('Improved Earthen Guard', 'guard', 'When you are successfully attacked, there is a chance that a Stone Skin will be cast on you.');
insert into effect(name, effect_type, description) values ('Vengeful', 'guard', 'When its wielder is hit in battle, this weapon has a 10% chance to cause him or her to become full of anger and go into a Rage.');
insert into effect(name, effect_type, description) values ('Life Shield', 'guard', 'Every time you are hit while wearing a Life Shield item there is a 10% chance you gain 15 temporary hitpoints that last for up to 1 minute.');

--insert into effect(name, effect_type) values ('', '');