-- Bane
insert into effect(name, effect_type) values ('Aberration Bane', 'bane');
insert into effect(name, effect_type) values ('Animal Bane', 'bane');
insert into effect(name, effect_type) values ('Chaotic Outsider Bane', 'bane');
insert into effect(name, effect_type) values ('Construct Bane', 'bane');
insert into effect(name, effect_type) values ('Dragon Bane', 'bane');
insert into effect(name, effect_type) values ('Elf Bane', 'bane');
insert into effect(name, effect_type) values ('Evil Outsider Bane', 'bane');
insert into effect(name, effect_type) values ('Human Bane', 'bane');
insert into effect(name, effect_type) values ('Humanoid Bane', 'bane');
insert into effect(name, effect_type) values ('Magical Beast Bane', 'bane');
insert into effect(name, effect_type) values ('Monstrous Humanoid Bane', 'bane');
insert into effect(name, effect_type) values ('Ooze Bane', 'bane');
insert into effect(name, effect_type) values ('Orc Bane', 'bane');
insert into effect(name, effect_type) values ('Reptilian Bane', 'bane');
insert into effect(name, effect_type) values ('Bane of the Unnatural', 'bane');
insert into effect(name, effect_type) values ('Elemental Bane', 'bane');
insert into effect(name, effect_type) values ('Feybane', 'bane');
insert into effect(name, effect_type) values ('Giant Bane', 'bane');
insert into effect(name, effect_type) values ('Giant Slayer', 'bane');
insert into effect(name, effect_type) values ('Plant Bane', 'bane');
insert into effect(name, effect_type) values ('Undead Bane', 'bane');
insert into effect(name, effect_type) values ('Unnatural Bane', 'bane');
insert into effect(name, effect_type) values ('Vermin Bane', 'bane');
insert into effect(name, effect_type) values ('Lawful Outsider Bane', 'bane');
-- Lesser bane
insert into effect(name, effect_type) values ('Lesser Aberration Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Animal Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Construct Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Dwarf Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Elemental Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Evil Outsider Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Goblinoid Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Halfling Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Human Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Incorporeal Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Monstrous Humanoid Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Ooze Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Undead Bane', 'bane');
insert into effect(name, effect_type) values ('Lesser Vermin Bane', 'bane');
-- Greater bane
insert into effect(name, effect_type) values ('Greater Aberration Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Animal Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Bane of the Unnatural', 'bane');
insert into effect(name, effect_type) values ('Greater Construct Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Dragon Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Elemental Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Elf Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Evil Outsider Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Giant Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Human Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Incorporeal Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Magical Beast Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Ooze Bane', 'bane');
insert into effect(name, effect_type) values ('Greater Undead Bane', 'bane');
--insert into effect(name, effect_type) values ('', 'bane');
-- Special bane
insert into effect(name, effect_type) values ('Extra damage vs Undead', 'bane');
insert into effect(name, effect_type) values ('vs Evil', 'bane');
