insert into item_skippable (name) values ('The Changestone');
insert into item_skippable (name) values ('Enchanted Chocolates by Fabiano & Zelda');
insert into item_skippable (name) values ('Seal of House Avithoul');
insert into item_skippable (name) values ('Seal of House Dun''Robar');
insert into item_skippable (name) values ('Seal of House Szind');
insert into item_skippable (name) values ('Planar Focus of Subterfuge');
insert into item_skippable (name) values ('Planar Focus of Prowess');
insert into item_skippable (name) values ('Planar Focus of Erudition');
insert into item_skippable (name) values ('Spider-spun Caparison');
insert into item_skippable (name) values ('Star of Day');
insert into item_skippable (name) values ('Spidersilk Robes');
insert into item_skippable (name) values ('Hide of the Goristro');
insert into item_skippable (name) values ('Terrorweb Chitin Breastplate');
insert into item_skippable (name) values ('Embrace of the Spider Queen');
insert into item_skippable (name) values ('Helm of the Black Dragon (Level 23)');
insert into item_skippable (name) values ('Helm of the Black Dragon (Level 24)');
insert into item_skippable (name) values ('Helm of the Black Dragon (Level 25)');
insert into item_skippable (name) values ('Helm of the White Dragon (Level 23)');
insert into item_skippable (name) values ('Helm of the White Dragon (Level 24)');
insert into item_skippable (name) values ('Helm of the White Dragon (Level 25)');
insert into item_skippable (name) values ('Helm of the Blue Dragon (Level 23)');
insert into item_skippable (name) values ('Helm of the Blue Dragon (Level 24)');
insert into item_skippable (name) values ('Helm of the Blue Dragon (Level 25)');
insert into item_skippable (name) values ('Intricate Field Optics (Level 23)');
insert into item_skippable (name) values ('Intricate Field Optics (Level 24)');
insert into item_skippable (name) values ('Intricate Field Optics (Level 25)');
insert into item_skippable (name) values ('Skullduggery Kit (Level 14)');
insert into item_skippable (name) values ('Skullduggery Kit (Level 15)');
insert into item_skippable (name) values ('Skullduggery Kit (Level 16)');
insert into item_skippable (name) values ('Skullduggery Kit (Level 25)');
insert into item_skippable (name) values ('Skullduggery Kit (Level 26)');
insert into item_skippable (name) values ('Skullduggery Kit (Level 27)');
insert into item_skippable (name) values ('Prisoner''s Manacles (Level 14)');
insert into item_skippable (name) values ('Prisoner''s Manacles (Level 15)');
insert into item_skippable (name) values ('Prisoner''s Manacles (Level 16)');
insert into item_skippable (name) values ('Prisoner''s Manacles (Level 25)');
insert into item_skippable (name) values ('Prisoner''s Manacles (Level 26)');
insert into item_skippable (name) values ('Prisoner''s Manacles (Level 27)');
insert into item_skippable (name) values ('Shade''s Hood (Level 14)');
insert into item_skippable (name) values ('Shade''s Hood (Level 15)');
insert into item_skippable (name) values ('Shade''s Hood (Level 16)');
insert into item_skippable (name) values ('Shade''s Hood (Level 25)');
insert into item_skippable (name) values ('Shade''s Hood (Level 26)');
insert into item_skippable (name) values ('Shade''s Hood (Level 27)');
insert into item_skippable (name) values ('Stolen Necklace (Level 14)');
insert into item_skippable (name) values ('Stolen Necklace (Level 15)');
insert into item_skippable (name) values ('Stolen Necklace (Level 16)');
insert into item_skippable (name) values ('Stolen Necklace (Level 25)');
insert into item_skippable (name) values ('Stolen Necklace (Level 26)');
insert into item_skippable (name) values ('Stolen Necklace (Level 27)');
insert into item_skippable (name) values ('Prison Break');
insert into item_skippable (name) values ('Fell Shiv (Level 14)');
insert into item_skippable (name) values ('Fell Shiv (Level 15)');
insert into item_skippable (name) values ('Fell Shiv (Level 16)');
insert into item_skippable (name) values ('Fell Shiv (Level 25)');
insert into item_skippable (name) values ('Fell Shiv (Level 26)');
insert into item_skippable (name) values ('Fell Shiv (Level 27)');
insert into item_skippable (name) values ('Goatskin Boots (Level 17)');
insert into item_skippable (name) values ('Goatskin Boots (Level 18)');
insert into item_skippable (name) values ('Goatskin Boots (Level 19)');
insert into item_skippable (name) values ('Goatskin Boots (Level 26)');
insert into item_skippable (name) values ('Goatskin Boots (Level 27)');
insert into item_skippable (name) values ('Goatskin Boots (Level 28)');
insert into item_skippable (name) values ('Master''s Riposte');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 17)');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 18)');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 19)');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 26)');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 27)');
insert into item_skippable (name) values ('Magistrate''s Scepter (Level 28)');
insert into item_skippable (name) values ('Elemental Fury');
insert into item_skippable (name) values ('Shadowmail (Level 16)');
insert into item_skippable (name) values ('Shadowmail (Level 17)');
insert into item_skippable (name) values ('Shadowmail (Level 18)');
insert into item_skippable (name) values ('Shadowmail (Level 23)');
insert into item_skippable (name) values ('Shadowmail (Level 24)');
insert into item_skippable (name) values ('Shadowmail (Level 25)');
insert into item_skippable (name) values ('Tainted Helm of Mystery');
insert into item_skippable (name) values ('Mysterious Ring');
insert into item_skippable (name) values ('Collective Sight');
insert into item_skippable (name) values ('Dream Edge');
insert into item_skippable (name) values ('Rahl''s Might');
insert into item_skippable (name) values ('Chimera''s Fang');
insert into item_skippable (name) values ('Belashyrra''s Cleansed Scepter');
insert into item_skippable (name) values ('Kindred Spirit');
insert into item_skippable (name) values ('Legendary Kindred Spirit');
insert into item_skippable (name) values ('Alpha Phase Goggles');
insert into item_skippable (name) values ('Beta Phase Goggles');
insert into item_skippable (name) values ('-1 Quarterstaff of Lesser Halfling Bane');
insert into item_skippable (name) values ('Rose Colored Goggles');
insert into item_skippable (name) values ('Steps'' Lenses of Seein'' Hidden Hand Secrets');
insert into item_skippable (name) values ('Dull Dagger');
insert into item_skippable (name) values ('Battleworn Chainshirt');
insert into item_skippable (name) values ('Battleworn Breastplate');
insert into item_skippable (name) values ('Battleworn Chainmail');
insert into item_skippable (name) values ('Ember Sickle');
insert into item_skippable (name) values ('Ember Heavy Mace');
insert into item_skippable (name) values ('Ember Great Axe');
insert into item_skippable (name) values ('Ember Longsword');
insert into item_skippable (name) values ('Ember Longbow');
insert into item_skippable (name) values ('Ember Rapier');
insert into item_skippable (name) values ('Ember Shortbow');
insert into item_skippable (name) values ('Toothpick');
insert into item_skippable (name) values ('Eye of Vol');
insert into item_skippable (name) values ('Urthullz Petrified Stalk');
insert into item_skippable (name) values ('Cold Fire');
insert into item_skippable (name) values ('Golem Gem');
insert into item_skippable (name) values ('Festival Luck Charms');
insert into item_skippable (name) values ('Official Risia Ice Games Ice Skates');
insert into item_skippable (name) values ('Boots of Grounding');
insert into item_skippable (name) values ('Prismatic Cloak, Violet (Level 19)');
insert into item_skippable (name) values ('Prismatic Cloak, Green (Level 19)');
insert into item_skippable (name) values ('Prismatic Cloak, Grey (Level 19)');
insert into item_skippable (name) values ('Prismatic Cloak, Blue (Level 19)');
insert into item_skippable (name) values ('Prismatic Cloak, Red (Level 19)');
insert into item_skippable (name) values ('Prismatic Cloak, Green (Level 18)');
insert into item_skippable (name) values ('Prismatic Cloak, Grey (Level 18)');
insert into item_skippable (name) values ('Prismatic Cloak, Red (Level 18)');
insert into item_skippable (name) values ('Prismatic Cloak, Violet (Level 18)');
insert into item_skippable (name) values ('Prismatic Cloak, Blue (Level 18)');
insert into item_skippable (name) values ('Prismatic Cloak, Green (Level 17)');
insert into item_skippable (name) values ('Prismatic Cloak, Grey (Level 17)');
insert into item_skippable (name) values ('Prismatic Cloak, Blue (Level 17)');
insert into item_skippable (name) values ('Prismatic Cloak, Red (Level 17)');
insert into item_skippable (name) values ('Prismatic Cloak, Violet (Level 17)');
insert into item_skippable (name) values ('Prismatic Cloak, Blue (Level 26)');
insert into item_skippable (name) values ('Prismatic Cloak, Blue (Level 27)');
insert into item_skippable (name) values ('Prismatic Cloak, Blue (Level 28)');
insert into item_skippable (name) values ('Prismatic Cloak, Green (Level 26)');
insert into item_skippable (name) values ('Prismatic Cloak, Green (Level 27)');
insert into item_skippable (name) values ('Prismatic Cloak, Green (Level 28)');
insert into item_skippable (name) values ('Prismatic Cloak, Grey (Level 26)');
insert into item_skippable (name) values ('Prismatic Cloak, Grey (Level 27)');
insert into item_skippable (name) values ('Prismatic Cloak, Grey (Level 28)');
insert into item_skippable (name) values ('Prismatic Cloak, Red (Level 26)');
insert into item_skippable (name) values ('Prismatic Cloak, Red (Level 27)');
insert into item_skippable (name) values ('Prismatic Cloak, Red (Level 28)');
insert into item_skippable (name) values ('Prismatic Cloak, Violet (Level 26)');
insert into item_skippable (name) values ('Prismatic Cloak, Violet (Level 27)');
insert into item_skippable (name) values ('Prismatic Cloak, Violet (Level 28)');
insert into item_skippable (name) values ('Malchor''s Undersun Goggles');
insert into item_skippable (name) values ('Legendary Collective Sight');
insert into item_skippable (name) values ('Epic Spare Hand');
insert into item_skippable (name) values ('Spare Hand (Level 7)');
insert into item_skippable (name) values ('Spare Hand (Level 11)');
insert into item_skippable (name) values ('Spare Hand (Level 15)');
insert into item_skippable (name) values ('Epic Rock Boots');
insert into item_skippable (name) values ('Rock Boots (Level 15)');
insert into item_skippable (name) values ('Rock Boots (level 7)');
insert into item_skippable (name) values ('Rock Boots (Level 11)');
insert into item_skippable (name) values ('Bracers of Wind (level 15)');
insert into item_skippable (name) values ('Epic Bracers of Wind');
insert into item_skippable (name) values ('Bracers of Wind (level 7)');
insert into item_skippable (name) values ('Bracers of Wind (level 11)');
insert into item_skippable (name) values ('Epic Cloak of Flames');
insert into item_skippable (name) values ('Cloak of Flames (level 7)');
insert into item_skippable (name) values ('Cloak of Flames (level 11)');
insert into item_skippable (name) values ('Cloak of Flames (level 15)');
insert into item_skippable (name) values ('Epic Ring of Master Artifice');
insert into item_skippable (name) values ('Ring of Master Artifice (Level 7)');
insert into item_skippable (name) values ('Ring of Master Artifice (Level 11)');
insert into item_skippable (name) values ('Epic Ring of the Stalker');
insert into item_skippable (name) values ('Ring of the Stalker (Level 11)');
insert into item_skippable (name) values ('Ring of Master Artifice (Level 15)');
insert into item_skippable (name) values ('Ring of the Stalker (Level 7)');
insert into item_skippable (name) values ('Ring of the Stalker (Level 15)');
insert into item_skippable (name) values ('Epic Blasting Chime');
insert into item_skippable (name) values ('Blasting Chime (Level 7)');
insert into item_skippable (name) values ('Blasting Chime (Level 11)');
insert into item_skippable (name) values ('Blasting Chime (Level 15)');
insert into item_skippable (name) values ('Epic Frozen Tunic');
insert into item_skippable (name) values ('Frozen Tunic (Level 12)');
insert into item_skippable (name) values ('Frozen Tunic (Level 16)');
insert into item_skippable (name) values ('Frozen Tunic (Level 8)');
insert into item_skippable (name) values ('Epic Mournlode Chain');
insert into item_skippable (name) values ('Mournlode Chain (Level 4)');
insert into item_skippable (name) values ('Mournlode Chain (level 12)');
insert into item_skippable (name) values ('Mournlode Chain (level 16)');
insert into item_skippable (name) values ('Mournlode Chain (level 8)');
insert into item_skippable (name) values ('Epic Mournlode Breastplate');
insert into item_skippable (name) values ('Mournlode Breastplate (Level 4)');
insert into item_skippable (name) values ('Mournlode Breastplate (level 12)');
insert into item_skippable (name) values ('Mournlode Breastplate (level 16)');
insert into item_skippable (name) values ('Mournlode Breastplate (level 8)');
insert into item_skippable (name) values ('Epic Mournlode Fullplate');
insert into item_skippable (name) values ('Mournlode Fullplate (Level 4)');
insert into item_skippable (name) values ('Mournlode Fullplate (level 12)');
insert into item_skippable (name) values ('Mournlode Fullplate (level 16)');
insert into item_skippable (name) values ('Mournlode Fullplate (level 8)');
insert into item_skippable (name) values ('Mournlode Light Mace (level 8)');
insert into item_skippable (name) values ('Mournlode Light Mace (level 12)');
insert into item_skippable (name) values ('Mournlode Light Mace (level 16)');
insert into item_skippable (name) values ('Epic Mournlode Light Mace');
insert into item_skippable (name) values ('Mournlode Greataxe (level 8)');
insert into item_skippable (name) values ('Elemental Greataxe of Fire (level 8)');
insert into item_skippable (name) values ('Mournlode Greataxe (level 12)');
insert into item_skippable (name) values ('Elemental Greataxe of Fire (level 12)');
insert into item_skippable (name) values ('Elemental Greataxe of Fire (level 16)');
insert into item_skippable (name) values ('Mournlode Greataxe (level 16)');
insert into item_skippable (name) values ('Epic Elemental Greataxe of Fire');
insert into item_skippable (name) values ('Epic Mournlode Greataxe');
insert into item_skippable (name) values ('Mournlode Longsword (level 8)');
insert into item_skippable (name) values ('Mournlode Longsword (level 12)');
insert into item_skippable (name) values ('Mournlode Longsword (level 16)');
insert into item_skippable (name) values ('Epic Mournlode Longsword');
insert into item_skippable (name) values ('Calomel Scimitar (level 8)');
insert into item_skippable (name) values ('Calomel Scimitar (level 12)');
insert into item_skippable (name) values ('Calomel Scimitar (level 16)');
insert into item_skippable (name) values ('Epic Calomel Scimitar');
insert into item_skippable (name) values ('Calomel Falchion (level 8)');
insert into item_skippable (name) values ('Calomel Falchion (level 12)');
insert into item_skippable (name) values ('Calomel Falchion (level 16)');
insert into item_skippable (name) values ('Epic Calomel Falchion');
insert into item_skippable (name) values ('Elemental Longbow of Earth (level 8)');
insert into item_skippable (name) values ('Calomel Strung Long Bow (level 8)');
insert into item_skippable (name) values ('Calomel Strung Long Bow (level 12)');
insert into item_skippable (name) values ('Elemental Longbow of Earth (level 12)');
insert into item_skippable (name) values ('Calomel Strung Long Bow (level 16)');
insert into item_skippable (name) values ('Elemental Longbow of Earth (level 16)');
insert into item_skippable (name) values ('Epic Calomel Long Bow');
insert into item_skippable (name) values ('Epic Elemental Longbow of Earth');
insert into item_skippable (name) values ('Mournlode Shortsword (level 8)');
insert into item_skippable (name) values ('Mournlode Shortsword (level 12)');
insert into item_skippable (name) values ('Mournlode Shortsword (level 16)');
insert into item_skippable (name) values ('Epic Mournlode Shortsword');
insert into item_skippable (name) values ('Elemental Rapier of Air (level 8)');
insert into item_skippable (name) values ('Calomel Rapier (level 8)');
insert into item_skippable (name) values ('Elemental Rapier of Air (level 12)');
insert into item_skippable (name) values ('Calomel Rapier (level 12)');
insert into item_skippable (name) values ('Elemental Rapier of Air (level 16)');
insert into item_skippable (name) values ('Calomel Rapier (level 16)');
insert into item_skippable (name) values ('Epic Calomel Rapier');
insert into item_skippable (name) values ('Epic Elemental Rapier of Air');
insert into item_skippable (name) values ('Mournlode Warhammer (level 8)');
insert into item_skippable (name) values ('Mournlode Warhammer (level 12)');
insert into item_skippable (name) values ('Mournlode Warhammer (level 16)');
insert into item_skippable (name) values ('Epic Mournlode Warhammer');
insert into item_skippable (name) values ('Mournlode Maul (level 8)');
insert into item_skippable (name) values ('Mournlode Maul (level 12)');
insert into item_skippable (name) values ('Mournlode Maul (level 16)');
insert into item_skippable (name) values ('Epic Mournlode Maul');
insert into item_skippable (name) values ('Elemental Khopesh of Water (level 8)');
insert into item_skippable (name) values ('Elemental Khopesh of Water (level 12)');
insert into item_skippable (name) values ('Elemental Khopesh of Water (level 16)');
insert into item_skippable (name) values ('Epic Elemental Khopesh of Water');
insert into item_skippable (name) values ('Calomel Studded Handwraps (level 8)');
insert into item_skippable (name) values ('Calomel Studded Handwraps (level 12)');
insert into item_skippable (name) values ('Calomel Studded Handwraps (level 16)');
insert into item_skippable (name) values ('Epic Calomel Studded Handwraps');
insert into item_skippable (name) values ('Gem of Many Facets');
insert into item_skippable (name) values ('Epic Gem of Many Facets');
insert into item_skippable (name) values ('Legendary Gem of Many Facets');
insert into item_skippable (name) values ('Elfcrafted Robe');
insert into item_skippable (name) values ('Elfcrafted Chain Armor');
insert into item_skippable (name) values ('Elfcrafted Chain Shirt');
insert into item_skippable (name) values ('Elfcrafted Plate Armor');
insert into item_skippable (name) values ('Robe of Arcane Power');
insert into item_skippable (name) values ('Romag''s Club of Earthen Dominion');
insert into item_skippable (name) values ('Drow Quarterstaff of the Weapon Master');
insert into item_skippable (name) values ('Drow Dagger of the Weapon Master');
insert into item_skippable (name) values ('Drow Light Mace of the Weapon Master');
insert into item_skippable (name) values ('Drow Greataxe of the Weapon Master');
insert into item_skippable (name) values ('Drow Longsword of the Weapon Master');
insert into item_skippable (name) values ('Drow Scimitar of the Weapon Master');
insert into item_skippable (name) values ('Drow Shortsword of the Weapon Master');
insert into item_skippable (name) values ('Drow Rapier of the Weapon Master');
insert into item_skippable (name) values ('Drow Warhammer of the Weapon Master');
insert into item_skippable (name) values ('Drow Maul of the Weapon Master');
insert into item_skippable (name) values ('Drow Bastard Sword of the Weapon Master');
insert into item_skippable (name) values ('Drow Khopesh of the Weapon Master');
insert into item_skippable (name) values ('Duergar Waraxe of the Weapon Master');
insert into item_skippable (name) values ('Spear of the Mournlands');
--insert into item_skippable (name) values ('');