-- Special effects
insert into effect(name, effect_type) values ('Everbright', 'special');
insert into effect(name, effect_type) values ('Finesse', 'special');
insert into effect(name, effect_type) values ('Flameblade', 'special');
insert into effect(name, effect_type) values ('Frostblade', 'special');
insert into effect(name, effect_type) values ('Frozen Aether', 'special');
insert into effect(name, effect_type) values ('Anchoring', 'special');
insert into effect(name, effect_type) values ('Acidic Reaping', 'special');

-- Strange stuff
insert into effect(name, effect_type) values ('Better Offhanded', 'special');
insert into effect(name, effect_type) values ('Bless Ward', 'special');
insert into effect(name, effect_type) values ('Blood Rage', 'special');
insert into effect(name, effect_type) values ('Bloodrage Defense', 'special');
insert into effect(name, effect_type) values ('Bloody Thorns', 'special');
insert into effect(name, effect_type) values ('Bone Paws', 'special');
insert into effect(name, effect_type) values ('Boon of Undeath', 'special');
insert into effect(name, effect_type) values ('Calamitous Blows', 'special');
insert into effect(name, effect_type, description) values ('Chaotic Curse', 'special', 'This property gives a chance to cast either bestow curse or remove curse on the wearer and attacker often when hit by melee attacks. Proc rate is about 10%. Standard short duration minimum lvl curse (-4 penalty to attacks, saves, et cetera).');
insert into effect(name, effect_type) values ('Chimera''s Vitality', 'special');
insert into effect(name, effect_type) values ('Choked by Mother Night', 'special');
insert into effect(name, effect_type) values ('Clever Strike', 'special');
insert into effect(name, effect_type, description) values ('Confounding Enchantment', 'special', 'The enchantment varies every time it''s equipped');
insert into effect(name, effect_type, description) values ('Cursed Level Drain', 'special', 'Each time the player equipping this item is hit there is a small chance it will drain 1 level (no save, almost nothing wards).');
insert into effect(name, effect_type) values ('Eidolon Summons', 'special');
insert into effect(name, effect_type) values ('Elemental Spiral', 'special');
insert into effect(name, effect_type) values ('Embodiment of Law', 'special');
insert into effect(name, effect_type) values ('Embrace of the Spider Queen', 'special');
insert into effect(name, effect_type) values ('Enhanced Jet Propulsion', 'special');
insert into effect(name, effect_type) values ('Epic Nimbleness', 'special');
insert into effect(name, effect_type) values ('Favored Weapon', 'special');
insert into effect(name, effect_type, description) values ('Feat', 'special', 'Need to be adjusted');
insert into effect(name, effect_type) values ('Feeds Off Madness', 'special');
insert into effect(name, effect_type) values ('Greater Boon of Undeath', 'special');
insert into effect(name, effect_type) values ('Greater Chimera''s Ferocity', 'special');
insert into effect(name, effect_type) values ('Greater Dragonmark Enhancement', 'special');
insert into effect(name, effect_type) values ('Greater Nimbleness', 'special');
insert into effect(name, effect_type) values ('Greater Stability', 'special');
insert into effect(name, effect_type) values ('Stability', 'special');
insert into effect(name, effect_type) values ('Sink Like a Brick', 'special');
insert into effect(name, effect_type) values ('Weighty Asset', 'special');
insert into effect(name, effect_type) values ('Swim like a Fish', 'special');
insert into effect(name, effect_type) values ('Jet Propulsion', 'special');
insert into effect(name, effect_type) values ('Wondrous Craftsmanship', 'special');
insert into effect(name, effect_type) values ('Kick ''Em While They''re Down', 'special');
insert into effect(name, effect_type) values ('Halcyon Mind', 'special');
insert into effect(name, effect_type) values ('Tet-zik, The Enlightened Change', 'special');
insert into effect(name, effect_type) values ('Legendary Tet-zik, The Enlightened Change', 'special');
insert into effect(name, effect_type) values ('Maker''s Touch', 'special');
insert into effect(name, effect_type) values ('High Spirits', 'special');
insert into effect(name, effect_type) values ('Shocking Blow', 'special');
insert into effect(name, effect_type) values ('Spike-Studded', 'special');
insert into effect(name, effect_type, description) values ('Temperance of Spirit', 'special', 'You have a +1 Quality Bonus to Physical Resistance Rating per Religious Lore Feat.');
insert into effect(name, effect_type, description) values ('Temperance of Belief', 'special', 'You have a +1 Quality Bonus to Magical Resistance Rating per Religious Lore Feat.');
insert into effect(name, effect_type) values ('Secret Door Detection', 'special');
insert into effect(name, effect_type) values ('Intercession Ward', 'special');
insert into effect(name, effect_type) values ('Winged Allure', 'special');
insert into effect(name, effect_type) values ('Transform Kinetic Energy', 'special');
insert into effect(name, effect_type) values ('The Mummy''s Gift', 'special');
insert into effect(name, effect_type) values ('Starter', 'special');
insert into effect(name, effect_type) values ('Scarab of Protection Ward', 'special');

-- ranged stuff
insert into effect(name, effect_type) values ('Arrow Spitting', 'special');
insert into effect(name, effect_type) values ('Conjure Ice Arrow', 'special');