-- General Combat
insert into effect(name, effect_type) values ('Accuracy', 'general_combat');
insert into effect(name, effect_type) values ('Armor Piercing', 'general_combat');
insert into effect(name, effect_type) values ('Deadly', 'general_combat');
insert into effect(name, effect_type) values ('Seeker', 'general_combat');
insert into effect(name, effect_type) values ('Deception', 'general_combat');
insert into effect(name, effect_type) values ('Dodge Bypass', 'general_combat');
insert into effect(name, effect_type) values ('Bonus to damage vs. helpless', 'general_combat');
insert into effect(name, effect_type) values ('Sneak Attack Dice', 'general_combat');
insert into effect(name, effect_type) values ('Fortification Bypass', 'general_combat');
insert into effect(name, effect_type) values ('Speed', 'general_combat');
--insert into effect(name, effect_type) values ('', 'general_combat');

-- DR Bypass
insert into effect(name, effect_type) values ('DR Bypass', 'dr_bypass');
insert into effect(name, effect_type) values ('Adamantine', 'dr_bypass');
insert into effect(name, effect_type) values ('Byeshk', 'dr_bypass');
insert into effect(name, effect_type) values ('Cold Iron', 'dr_bypass');
insert into effect(name, effect_type) values ('Crystal', 'dr_bypass');
insert into effect(name, effect_type) values ('Flametouched Iron', 'dr_bypass');
insert into effect(name, effect_type) values ('Silver', 'dr_bypass');
insert into effect(name, effect_type) values ('Aligned', 'dr_bypass');
insert into effect(name, effect_type) values ('Metalline', 'dr_bypass');
insert into effect(name, effect_type, description) values ('Righteous', 'dr_bypass', 'This weapon is imbued with holy power, giving it an additional +2 to attack bonus and damage against any evil creature. This power makes the weapon good-aligned.');

-- Tactical
insert into effect(name, effect_type) values ('Assassinate', 'tactical');
insert into effect(name, effect_type) values ('Breath Weapon Focus', 'tactical');
insert into effect(name, effect_type) values ('Dazing', 'tactical');
insert into effect(name, effect_type, description) values ('Sundering', 'tactical', 'On Hit: Your target suffers a -1 Penalty to Fortitude Saving Throws for 6 seconds. This effect stacks up to 5 times. This effect may only occur on-hit once every three seconds.');
insert into effect(name, effect_type) values ('Stunning', 'tactical');
insert into effect(name, effect_type) values ('Vertigo', 'tactical');
insert into effect(name, effect_type) values ('Shatter', 'tactical');
insert into effect(name, effect_type) values ('Sunder', 'tactical');
insert into effect(name, effect_type) values ('Combat Mastery', 'tactical');

-- Melee
insert into effect(name, effect_type) values ('Incite', 'general_combat');
insert into effect(name, effect_type) values ('Diversion', 'melee_combat');
insert into effect(name, effect_type) values ('Melee Alacrity', 'melee_combat');
insert into effect(name, effect_type) values ('Melee Power', 'melee_combat');
insert into effect(name, effect_type) values ('Doublestrike', 'melee_combat');

-- Ranged
insert into effect(name, effect_type, description) values ('Ranged Power', 'ranged_combat', 'Increase the damage of ranged attacks');
insert into effect(name, effect_type, description) values ('Distant Diversion', 'ranged_combat', 'ranged treath reduction');
insert into effect(name, effect_type, description) values ('Ranged Alacrity', 'ranged_combat', 'Ranged attack speed');
insert into effect(name, effect_type, description) values ('Doubleshot', 'ranged_combat', 'chanche to make another ranged attack');

insert into effect(name, effect_type, description) values ('Venomed Ammunition', 'ranged_combat', 'Adds venom damage to ranged attacks');
insert into effect(name, effect_type, description) values ('Burning Ammunition', 'ranged_combat', 'Adds fire damage to ranged attacks');
insert into effect(name, effect_type, description) values ('Blunted Ammunition', 'ranged_combat', 'Adds blunt to damage types to ranged attacks');

-- Threat range
insert into effect(name, effect_type) values ('Elasticity', 'ranged_combat');
insert into effect(name, effect_type) values ('Impact', 'general_combat');
insert into effect(name, effect_type) values ('Keen', 'general_combat');

-- Special Weapon Procs that buffs
insert into effect(name, effect_type) values ('Cannith Combat Infusion', 'weapon_proc');
insert into effect(name, effect_type) values ('Enhanced Bloodrage', 'weapon_proc');
insert into effect(name, effect_type) values ('Enhanced Ki', 'weapon_proc');
insert into effect(name, effect_type) values ('Feeding', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Affirmation', 'weapon_proc');

-- Special Weapon Procs
insert into effect(name, effect_type) values ('Accursed Flame', 'weapon_proc');
insert into effect(name, effect_type) values ('Acid Arrow', 'weapon_proc');
insert into effect(name, effect_type) values ('Alchemical Air Attunement', 'weapon_proc');
insert into effect(name, effect_type) values ('Alchemical Earth Attunement', 'weapon_proc');
insert into effect(name, effect_type) values ('Alchemical Fire Attunement', 'weapon_proc');
insert into effect(name, effect_type) values ('Alchemical Water Attunement', 'weapon_proc');
insert into effect(name, effect_type) values ('Anti-Magic Runes', 'weapon_proc');
insert into effect(name, effect_type) values ('Antimagic Spike', 'weapon_proc');
insert into effect(name, effect_type) values ('Antipodal', 'weapon_proc');
insert into effect(name, effect_type) values ('Banishing', 'weapon_proc');
insert into effect(name, effect_type) values ('Banishing Fists', 'weapon_proc');
insert into effect(name, effect_type) values ('Blinding Embers', 'weapon_proc');
insert into effect(name, effect_type) values ('Blunt Trauma', 'weapon_proc');
insert into effect(name, effect_type) values ('Bodyfeeder', 'weapon_proc');
insert into effect(name, effect_type) values ('Boneshatter', 'weapon_proc');
insert into effect(name, effect_type) values ('Bonesplitter', 'weapon_proc');
insert into effect(name, effect_type) values ('Brazen Brilliance', 'weapon_proc');
insert into effect(name, effect_type) values ('Cacophony', 'weapon_proc');
insert into effect(name, effect_type) values ('Cloudburst', 'weapon_proc');
insert into effect(name, effect_type) values ('Conflagrating', 'weapon_proc');
insert into effect(name, effect_type) values ('Corrosive Salt', 'weapon_proc');
insert into effect(name, effect_type) values ('Crushing Wave', 'weapon_proc');
insert into effect(name, effect_type) values ('Cursed Maelstrom', 'weapon_proc');
insert into effect(name, effect_type) values ('Disease: Unholy Tear', 'weapon_proc');
insert into effect(name, effect_type) values ('Disintegration', 'weapon_proc');
insert into effect(name, effect_type) values ('Disruption', 'weapon_proc');
insert into effect(name, effect_type) values ('Dripping with Magma', 'weapon_proc');
insert into effect(name, effect_type) values ('Felling the Oak', 'weapon_proc');
insert into effect(name, effect_type) values ('Earthgrab', 'weapon_proc');
insert into effect(name, effect_type) values ('Entropic', 'weapon_proc');
insert into effect(name, effect_type) values ('Epic Freezing Ice', 'weapon_proc');
insert into effect(name, effect_type) values ('Epic Goldcurse', 'weapon_proc');
insert into effect(name, effect_type) values ('Epic Noxious Venom Spike', 'weapon_proc');
insert into effect(name, effect_type) values ('Epic Telekinetic', 'weapon_proc');
insert into effect(name, effect_type) values ('Epic Trap the Soul', 'weapon_proc');
insert into effect(name, effect_type) values ('Eternal Fire', 'weapon_proc');
insert into effect(name, effect_type) values ('Eternal Holy Burst', 'weapon_proc');
insert into effect(name, effect_type) values ('Fiery Detonation', 'weapon_proc');
insert into effect(name, effect_type) values ('Flamebitten', 'weapon_proc');
insert into effect(name, effect_type) values ('Fracturing', 'weapon_proc');
insert into effect(name, effect_type) values ('Freezing Ice', 'weapon_proc');
insert into effect(name, effect_type) values ('Frostbite', 'weapon_proc');
insert into effect(name, effect_type) values ('Glass Jaw Strike', 'weapon_proc');
insert into effect(name, effect_type) values ('Glass Shards', 'weapon_proc');
insert into effect(name, effect_type) values ('Godly Wrath', 'weapon_proc');
insert into effect(name, effect_type) values ('Goldcurse', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Acid Arrow', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Dispelling', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Disruption', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Electric Storm', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Incineration', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Maiming', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Shocking Blow', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Shrieking Bolt', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Sirocco', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Stone Prison', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Sunburst', 'weapon_proc');
insert into effect(name, effect_type) values ('Greater Vorpal', 'weapon_proc');
insert into effect(name, effect_type) values ('Magma Surge', 'weapon_proc');
insert into effect(name, effect_type) values ('Sound and Silence', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Electric Storm', 'weapon_proc');
insert into effect(name, effect_type) values ('Scorching Sun', 'weapon_proc');
insert into effect(name, effect_type) values ('Stormreaver''s Thunderclap', 'weapon_proc');
insert into effect(name, effect_type) values ('Sovereign Lightning Strike', 'weapon_proc');
insert into effect(name, effect_type) values ('Manslayer', 'weapon_proc');
insert into effect(name, effect_type) values ('Shadow Spike', 'weapon_proc');
insert into effect(name, effect_type) values ('Noxious Venom Spike', 'weapon_proc');
insert into effect(name, effect_type) values ('Thunderstruck', 'weapon_proc');
insert into effect(name, effect_type) values ('The Golden Curse', 'weapon_proc');
insert into effect(name, effect_type) values ('Spiked', 'weapon_proc');
insert into effect(name, effect_type) values ('Minor Freezing Ice', 'weapon_proc');
insert into effect(name, effect_type) values ('Staggering Blow', 'weapon_proc');
insert into effect(name, effect_type) values ('Unstoppable Staggering Blow', 'weapon_proc');
insert into effect(name, effect_type) values ('Maiming', 'weapon_proc');
insert into effect(name, effect_type) values ('Vampirism', 'weapon_proc');
insert into effect(name, effect_type) values ('Hardened Spikes', 'weapon_proc');
insert into effect(name, effect_type, description) values ('Vile Grip of the Hidden Hand', 'weapon_proc', 'Attacks and offensive spells have a small chance to deal massive evil damage.');
insert into effect(name, effect_type, description) values ('Legendary Vile Grip of the Hidden Hand', 'weapon_proc', 'Attacks and offensive spells have a small chance to deal massive evil damage.');
insert into effect(name, effect_type) values ('Tidal', 'weapon_proc');
insert into effect(name, effect_type) values ('Mortal Strike', 'weapon_proc');
insert into effect(name, effect_type) values ('Mother Night''s Embrace', 'weapon_proc');
insert into effect(name, effect_type) values ('Stone Prison', 'weapon_proc');
insert into effect(name, effect_type, description) values ('Telekinetic', 'weapon_proc', 'Targets that suffer a critical hit from a Telekinetic weapon must make a DC 17 Balance check or be knocked down.');
insert into effect(name, effect_type, description) values ('Slicing Winds', 'weapon_proc', 'This weapon stores the cyclonic might of a windstorm within. When this weapon is used, this power can come to the surface as a series of rushing, cutting winds that deal slashing damage to the target over several seconds.');
insert into effect(name, effect_type, description) values ('Shockwave', 'weapon_proc', 'On Vorpal, this weapon triggers a Shockwave, striking its target with bludgeoning damage and dealing damage to surrounding enemies.');
insert into effect(name, effect_type) values ('Incineration', 'weapon_proc');
insert into effect(name, effect_type, description) values ('Rockslide', 'weapon_proc', 'This weapon stores the power of a volatile rockslide deep within. On hit, there is a chance to do massive bludgeoning damage to your enemy.');
insert into effect(name, effect_type) values ('Transmuted Platinum (Epic)', 'weapon_proc');
insert into effect(name, effect_type) values ('Lightning Strike', 'weapon_proc');
insert into effect(name, effect_type) values ('Improved Banishing', 'weapon_proc');
insert into effect(name, effect_type, description) values ('The Falling Star', 'weapon_proc', 'On hit, this weapon has a chance to put down a falling star upon your foes, dealing 90d6 Fire Damage and 30d6 Bludgeoning Damage to enemies caught within the blast. This blast is so powerful it has a chance to knock nearby enemies down upon impact.');
insert into effect(name, effect_type, description) values ('Thrill of the Hunt', 'weapon_proc', 'On Hit: You have a small chance to attempt to hold a monster in place. Even if the Hold is unsuccessful, their will saves will be reduced by 5.');
insert into effect(name, effect_type) values ('Sovereign Vorpal', 'weapon_proc');
insert into effect(name, effect_type) values ('Touch of the Mournlands', 'weapon_proc');
insert into effect(name, effect_type) values ('Inflict Blight', 'weapon_proc');
insert into effect(name, effect_type, description) values ('Sun Burst', 'weapon_proc', 'This weapon flashes an intense burst of sunlight on any critical hit. The target is blasted for 6 to 36 of light damage and is blinded as well. Oozes and Undead take 12 to 72 light damage. A successful DC 22 Reflex save reduces the damage by half and negates the blindness.');
insert into effect(name, effect_type) values ('Legendary Magma Surge', 'weapon_proc');
insert into effect(name, effect_type) values ('Overwhelming Incineration', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Trap the Soul', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Stone Prison', 'weapon_proc');
insert into effect(name, effect_type) values ('Slicing', 'weapon_proc');
insert into effect(name, effect_type) values ('Vorpal', 'weapon_proc');
insert into effect(name, effect_type) values ('Improved Disruption', 'weapon_proc');
insert into effect(name, effect_type) values ('Superior Disruption', 'weapon_proc');
insert into effect(name, effect_type) values ('Sovereign Disruption', 'weapon_proc');
insert into effect(name, effect_type) values ('Improved Vorpal', 'weapon_proc');
insert into effect(name, effect_type) values ('Superior Vorpal', 'weapon_proc');
insert into effect(name, effect_type) values ('Vicious', 'weapon_proc');
insert into effect(name, effect_type) values ('Negative Energy Spike', 'weapon_proc');
insert into effect(name, effect_type) values ('Lesser Vampirism', 'weapon_proc');
insert into effect(name, effect_type) values ('Slay Living', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Slay Living', 'weapon_proc');
insert into effect(name, effect_type) values ('Sovereign Banishing', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Freezing Ice', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Goldcurse', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Paralysis', 'weapon_proc');
insert into effect(name, effect_type, description) values ('Stench', 'weapon_proc', 'This weapon creates a near paralyzing stench. On critical hits the target becomes nauseous, severely slowing its movement rate.');
insert into effect(name, effect_type) values ('Sovereign Nightmares', 'weapon_proc');
insert into effect(name, effect_type) values ('Smiting', 'weapon_proc');
insert into effect(name, effect_type) values ('Sovereign Smiting', 'weapon_proc');
insert into effect(name, effect_type) values ('Overwhelming Shockwave', 'weapon_proc');
insert into effect(name, effect_type, description) values ('Thorny Crown of Madness', 'weapon_proc', 'This legendary weapon resonates with cruel and delightful madness. Strikes with this weapon have a chance to confuse your target, allowing them to harm and be harmed by friend and foe alike. Furthermore, hits with this weapon against Confused targets deal an additional Xd6 Chaos damage.');
insert into effect(name, effect_type) values ('Legendary Slicing Winds', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Telekinetic', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Sirocco', 'weapon_proc');
insert into effect(name, effect_type) values ('Sirocco', 'weapon_proc');
insert into effect(name, effect_type) values ('rd Degree Burns', 'weapon_proc');
insert into effect(name, effect_type) values ('Utter Disintegration', 'weapon_proc');
insert into effect(name, effect_type) values ('Stealer of Souls', 'weapon_proc');
insert into effect(name, effect_type) values ('Overwhelming Stealer of Souls', 'weapon_proc');
insert into effect(name, effect_type) values ('Nightmares', 'weapon_proc');
insert into effect(name, effect_type) values ('Skybreaker', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Stealer of Souls', 'weapon_proc');
insert into effect(name, effect_type) values ('Peals of Thunder', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Blinding Embers', 'weapon_proc');
insert into effect(name, effect_type) values ('Harnessed Lightning', 'weapon_proc');
insert into effect(name, effect_type) values ('Life Shield (Weapon)', 'weapon_proc');
insert into effect(name, effect_type) values ('Improved Acid Arrow', 'weapon_proc');
insert into effect(name, effect_type) values ('Superior Acid Arrow', 'weapon_proc');
insert into effect(name, effect_type) values ('Sovereign Acid Arrow', 'weapon_proc');
insert into effect(name, effect_type, description) values ('Light Bringer', 'weapon_proc', 'On Vorpal Hit: If an undead struck by this weapon has fewer than 1000 Hit Points, it is instantly slain. If the undead has above 1000 hit points, it takes 100 damage.');
insert into effect(name, effect_type, description) values ('Memory of Chains Broken', 'weapon_proc', 'Your hits have a 5% chance to Paralyze enemies for 5 seconds.');
insert into effect(name, effect_type) values ('Whelming Shockwave', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Whelming Shockwave', 'weapon_proc');
insert into effect(name, effect_type) values ('Lesser Boneshatter', 'weapon_proc');
insert into effect(name, effect_type) values ('Improved Smiting', 'weapon_proc');
insert into effect(name, effect_type) values ('Rock Shattering', 'weapon_proc');
insert into effect(name, effect_type) values ('Thunderclap', 'weapon_proc');
insert into effect(name, effect_type, description) values ('Life-Devouring', 'weapon_proc', 'This weapon deprives an enemy of its energy and passes it on to you. When you roll a 20 on an attack, the enemy must make a DC 28 Fortitude save or be subjected to a -6 penalty to all stats. At the same time you will feel your power return, as though Greater Restoration were cast on you. (Greater Restoration cures all temporary ability damage, restores all negative levels suffered from energy drain, and eliminates fatigue, exhaustion, confusion, and insanity suffered by you.)');
insert into effect(name, effect_type, description) values ('Strength Sapping', 'weapon_proc', 'Every time this weapon deals damage, the target must succeed on a Fortitude save (DC 15) or become exhausted.');
insert into effect(name, effect_type) values ('Thaarak Corrosion', 'weapon_proc');
insert into effect(name, effect_type) values ('Lifedrinker', 'weapon_proc');
insert into effect(name, effect_type) values ('Soul Eating', 'weapon_proc');
insert into effect(name, effect_type) values ('Legendary Acid Torrent', 'weapon_proc');
--insert into effect(name, effect_type) values ('', 'weapon_proc');

-- Keeper
insert into effect(name, effect_type) values ('First Litany of the Crimson Covenant', 'special');
insert into effect(name, effect_type) values ('Second Litany of the Crimson Covenant', 'special');
insert into effect(name, effect_type) values ('Third Litany of the Crimson Covenant', 'special');
insert into effect(name, effect_type) values ('Final Litany of the Crimson Covenant', 'special');

