insert into effect_alias (name, description) values ('Absorb Beholder and Doomsphere Spells', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Absorb Beholder and Doomsphere Spells', 'Absorb Beholder Spells', NULL, NULL);
insert into effect_alias (name, description) values ('Absorb Doomsphere Spells', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Absorb Doomsphere Spells', 'Absorb Beholder Spells', NULL, NULL);
insert into effect_alias (name, description) values ('Accuracy V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Accuracy V', 'Accuracy', 'Competence', 5);
insert into effect_alias (name, description) values ('Accuracy VI', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Accuracy VI', 'Accuracy', 'Competence', 6);
insert into effect_alias (name, description) values ('Accuracy VIII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Accuracy VIII', 'Accuracy', 'Competence', 8);
insert into effect_alias (name, description) values ('Accuracy IX', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Accuracy IX', 'Accuracy', 'Competence', 9);
insert into effect_alias (name, description) values ('Accuracy X', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Accuracy X', 'Accuracy', 'Competence', 10);
insert into effect_alias (name, description) values ('Acid Guard VIII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Acid Guard VIII', 'Acid Guard', NULL, 8);
insert into effect_alias (name, description) values ('Acid Lore IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Acid Lore IV', 'Acid Lore', 'Equipment', 14);
insert into effect_alias (name, description) values ('Axeblock II', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Axeblock II', 'Axeblock', NULL, 2);
insert into effect_alias (name, description) values ('Axeblock III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Axeblock III', 'Axeblock', NULL, 3);
insert into effect_alias (name, description) values ('Axeblock V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Axeblock V', 'Axeblock', NULL, 5);
insert into effect_alias (name, description) values ('Axeblock VI', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Axeblock VI', 'Axeblock', NULL, 6);
insert into effect_alias (name, description) values ('Axeblock X', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Axeblock X', 'Axeblock', NULL, 10);
insert into effect_alias (name, description) values ('Brilliant Silver Scales', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Brilliant Silver Scales', 'Cold Resistance', 'Enhancement', 52);
insert into effect_alias (name, description) values ('Blackscale Ferocity', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Blackscale Ferocity', 'Haste guard', NULL, NULL);
insert into effect_alias (name, description) values ('Charisma Skills - Exceptional Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Charisma Skills - Exceptional Bonus', 'Charisma Skills', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Competence Healing Amplification', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Competence Healing Amplification', 'Healing Amplification', 'Competence', NULL);
insert into effect_alias (name, description) values ('Competence Elemental Resistance', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Competence Elemental Resistance', 'Elemental Resistance', 'Competence', NULL);
insert into effect_alias (name, description) values ('Conjuration Focus III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Conjuration Focus III', 'Conjuration Focus', 'Equipment', 3);
insert into effect_alias (name, description) values ('Conjuration Focus V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Conjuration Focus V', 'Conjuration Focus', 'Equipment', 5);
insert into effect_alias (name, description) values ('Constitution Skills - Exceptional Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Constitution Skills - Exceptional Bonus', 'Constitution Skills', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Curse of Clumsiness', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Curse of Clumsiness', 'Dexterity', 'Penality', -1);
insert into effect_alias (name, description) values ('Curse of Dullness', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Curse of Dullness', 'Intelligence', 'Penality', -1);
insert into effect_alias (name, description) values ('Curse of Foolishness', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Curse of Foolishness', 'Wisdom', 'Penality', -1);
insert into effect_alias (name, description) values ('Curse of Repulsiveness', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Curse of Repulsiveness', 'Charisma', 'Penality', -1);
insert into effect_alias (name, description) values ('Damage Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Damage Bonus', 'Deadly', 'Competence', NULL);
insert into effect_alias (name, description) values ('Dark Restoration Lore', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dark Restoration Lore', 'Negative Lore', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dark Restoration Lore', 'Positive Lore', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Power of the Dark Restoration', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Dark Restoration', 'Nullification', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Dark Restoration', 'Devotion', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Command', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Command', 'Charisma Skills', 'Competence', 2);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Command', 'Hide', 'Penality', -6);
insert into effect_alias (name, description) values ('Dazing IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing IV', 'Dazing', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing IV', 'Stunning', 'Enhancement', 8);
insert into effect_alias (name, description) values ('Dazing V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing V', 'Dazing', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing V', 'Stunning', 'Enhancement', 10);
insert into effect_alias (name, description) values ('Dazing VI', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing VI', 'Dazing', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing VI', 'Stunning', 'Enhancement', 11);
insert into effect_alias (name, description) values ('Dazing VII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing VII', 'Dazing', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing VII', 'Stunning', 'Enhancement', 12);
insert into effect_alias (name, description) values ('Dazing VIII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing VIII', 'Dazing', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing VIII', 'Stunning', 'Enhancement', 13);
insert into effect_alias (name, description) values ('Dazing IX', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing IX', 'Dazing', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing IX', 'Stunning', 'Enhancement', 14);
insert into effect_alias (name, description) values ('Dazing X', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing X', 'Dazing', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dazing X', 'Stunning', 'Enhancement', 15);
insert into effect_alias (name, description) values ('Deadly VIII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deadly VIII', 'Deadly','Compentence' , 8);
insert into effect_alias (name, description) values ('Deadly X', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deadly X', 'Deadly','Compentence' , 10);
insert into effect_alias (name, description) values ('Lifesealed', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Lifesealed', 'Deathblock', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Lifesealed', 'Negative Energy Absorption', 'Enhancement', NULL);
insert into effect_alias (name, description) values ('Deathblock II', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock II', 'Deathblock', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock II', 'Negative Energy Absorption', 'Enhancement', 6);
insert into effect_alias (name, description) values ('Deathblock IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock IV', 'Deathblock', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock IV', 'Negative Energy Absorption', 'Enhancement', 12);
insert into effect_alias (name, description) values ('Deathblock VI', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock VI', 'Deathblock', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock VI', 'Negative Energy Absorption', 'Enhancement', 18);
insert into effect_alias (name, description) values ('Deathblock VII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock VII', 'Deathblock', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock VII', 'Negative Energy Absorption', 'Enhancement', 21);
insert into effect_alias (name, description) values ('Deathblock VIII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock VIII', 'Deathblock', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock VIII', 'Negative Energy Absorption', 'Enhancement', 24);
insert into effect_alias (name, description) values ('Deathblock IX', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock IX', 'Deathblock', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Deathblock IX', 'Negative Energy Absorption', 'Enhancement', 27);
insert into effect_alias (name, description) values ('Demonic Might', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Demonic Might', 'Strenght', 'Profane', 2);
insert into effect_alias (name, description) values ('Determined Reflex Save', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Determined Reflex Save', 'Reflex Save', 'Determination', 2);
insert into effect_alias (name, description) values ('Devil''s Blood', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Devil''s Blood', 'Curse Immunity', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Devil''s Blood', 'Poison Immunity', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Devil''s Blood', 'Fear Immunity', NULL, NULL);
insert into effect_alias (name, description) values ('Devil''s Bones', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Devil''s Bones', 'Fire Absorption', 'Enhancement', 23);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Devil''s Bones', 'Evil Absorption', 'Enhancement', 23);
insert into effect_alias (name, description) values ('Hound''s Blood', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Hound''s Blood', 'Charm Immunity', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Hound''s Blood', 'Poison Immunity', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Hound''s Blood', 'Pietrification Immunity', NULL, NULL);
insert into effect_alias (name, description) values ('Hound''s Bones', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Hound''s Bones', 'Acid Absorption', 'Enhancement', 23);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Hound''s Bones', 'Evil Absorption', 'Enhancement', 23);
insert into effect_alias (name, description) values ('Dexterity Skills - Exceptional Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Dexterity Skills - Exceptional Bonus', 'Dexterity Skills', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Diversion 20% (Insight)', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Diversion 20% (Insight)', 'Diversion', 'Insightful', 20);
insert into effect_alias (name, description) values ('Enchantment Focus I', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enchantment Focus I', 'Enchantment Focus', 'Equipment', 1);
insert into effect_alias (name, description) values ('Enchantment Focus II', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enchantment Focus II', 'Enchantment Focus', 'Equipment', 2);
insert into effect_alias (name, description) values ('Enchantment Focus III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enchantment Focus III', 'Enchantment Focus', 'Equipment', 3);
insert into effect_alias (name, description) values ('Enchantment Focus IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enchantment Focus IV', 'Enchantment Focus', 'Equipment', 4);
insert into effect_alias (name, description) values ('Enchantment Focus V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enchantment Focus V', 'Enchantment Focus', 'Equipment', 5);
insert into effect_alias (name, description) values ('Energy Siphon V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Energy Siphon V', 'Energy Siphon ', NULL, 25);
insert into effect_alias (name, description) values ('Energy Siphon X', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Energy Siphon X', 'Energy Siphon ', NULL, 50);
insert into effect_alias (name, description) values ('Energy Siphon XII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Energy Siphon XII', 'Energy Siphon ', NULL, 60);
insert into effect_alias (name, description) values ('Enhanced Balance', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enhanced Balance', 'Balance', 'Enhancement', NULL);
insert into effect_alias (name, description) values ('Enhanced Concentration', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enhanced Concentration', 'Concentration', 'Enhancement', NULL);
insert into effect_alias (name, description) values ('Enhanced Disable Device', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enhanced Disable Device', 'Disable Device', 'Enhancement', NULL);
insert into effect_alias (name, description) values ('Enhanced Jump', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enhanced Jump', 'Jump', 'Enhancement', NULL);
insert into effect_alias (name, description) values ('Enhanced Open Lock', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enhanced Open Lock', 'Open Lock', 'Enhancement', NULL);
insert into effect_alias (name, description) values ('Enhanced Perform', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enhanced Perform', 'Perform', 'Enhancement', NULL);
insert into effect_alias (name, description) values ('Enhanced Search', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Enhanced Search', 'Search', 'Enhancement', NULL);
insert into effect_alias (name, description) values ('Epic False Life', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Epic False Life', 'False Life', 'Enhancement', 45);
insert into effect_alias (name, description) values ('Equipment Healing Amplification', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Equipment Healing Amplification', 'Healing Amplification', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Equipped Healing Amplification', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Equipped Healing Amplification', 'Healing Amplification', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Eversight', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Eversight', 'True Sight', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Eversight', 'Blindness Immunity', NULL, NULL);
insert into effect_alias (name, description) values ('Evocation Focus I', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Evocation Focus I', 'Evocation Focus', 'Equipment', 1);
insert into effect_alias (name, description) values ('Evocation Focus II', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Evocation Focus II', 'Evocation Focus', 'Equipment', 2);
insert into effect_alias (name, description) values ('Evocation Focus III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Evocation Focus III', 'Evocation Focus', 'Equipment', 3);
insert into effect_alias (name, description) values ('Evocation Focus IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Evocation Focus IV', 'Evocation Focus', 'Equipment', 4);
insert into effect_alias (name, description) values ('Evocation Focus V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Evocation Focus V', 'Evocation Focus', 'Equipment', 5);
insert into effect_alias (name, description) values ('Exceptional Alluring Skills Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Alluring Skills Bonus', 'Alluring Skills Bonus', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Astute Skills Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Astute Skills Bonus', 'Astute Skills Bonus', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Intelligence Skills - Exceptional Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Intelligence Skills - Exceptional Bonus', 'Astute Skills Bonus', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Nimble Skills Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Nimble Skills Bonus', 'Nimble Skills Bonus', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Prudent Skills Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Prudent Skills Bonus', 'Prudent Skills Bonus', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Charisma', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Charisma', 'Charisma', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Strength', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Strength', 'Strength', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Dexterity', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Dexterity', 'Dexterity', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Constitution', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Constitution', 'Constitution', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Intelligence', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Intelligence', 'Intelligence', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Wisdom', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Wisdom', 'Wisdom', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Fortification', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Fortification', 'Fortification', 'Insightful', NULL);
insert into effect_alias (name, description) values ('Exceptional Healing Amplification', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Healing Amplification', 'Healing Amplification', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Nullification', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Nullification', 'Nullification', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Resistance', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Resistance', 'Resistance', 'Exceptional', NULL);
insert into effect_alias (name, description) values ('Exceptional Seeker', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Exceptional Seeker', 'Seeker', 'Insightful', NULL);
insert into effect_alias (name, description) values ('Fire Guard I', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Fire Guard I', 'Fire Guard', NULL, 1);
insert into effect_alias (name, description) values ('Fire Guard II', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Fire Guard II', 'Fire Guard', NULL, 2);
insert into effect_alias (name, description) values ('Fire Guard III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Fire Guard III', 'Fire Guard', NULL, 3);
insert into effect_alias (name, description) values ('Fire Guard VIII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Fire Guard VIII', 'Fire Guard', NULL, 8);
insert into effect_alias (name, description) values ('Fire Guard X', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Fire Guard X', 'Fire Guard', NULL, 10);
insert into effect_alias (name, description) values ('Fire Lore II', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Fire Lore II', 'Fire Lore', 'Equipment', 12);
insert into effect_alias (name, description) values ('Fire Lore III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Fire Lore III', 'Fire Lore', 'Equipment', 13);
insert into effect_alias (name, description) values ('Fire Lore VIII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Fire Lore VIII', 'Fire Lore', 'Equipment', 18);
insert into effect_alias (name, description) values ('Fleshmaker', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Fleshmaker', 'Healing Amplification', 'Enhancement', 20);
insert into effect_alias (name, description) values ('Greater False Life', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Greater False Life', 'Hit Points', 'Enhancement', 30);
insert into effect_alias (name, description) values ('Greater Elemental Energy', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Greater Elemental Energy', 'Hit Points', 'gee', 20); --Stacks with everything
insert into effect_alias (name, description) values ('Greater Elemental Spell Power', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Greater Elemental Spell Power', 'Wizardry', 'gesp', 100); --Stacks with everything
insert into effect_alias (name, description) values ('Archmagi', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Archmagi', 'Wizardry', 'Enhancement', 200);
insert into effect_alias (name, description) values ('Greater Twilight', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Greater Twilight', 'Arcane Casting Dexterity', 'Enhancement', 20);
insert into effect_alias (name, description) values ('Greater Arcane Casting Dexterity', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Greater Arcane Casting Dexterity', 'Arcane Casting Dexterity', 'Enhancement', 15);
insert into effect_alias (name, description) values ('Arcane Casting Dexterity', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Arcane Casting Dexterity', 'Arcane Casting Dexterity', 'Enhancement', 10);
insert into effect_alias (name, description) values ('Hammerblock V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Hammerblock V', 'Hammerblock', NULL, 10);
insert into effect_alias (name, description) values ('Hammerblock VII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Hammerblock VII', 'Hammerblock', NULL, 14);
insert into effect_alias (name, description) values ('Hardened Exterior', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Hardened Exterior', 'Armor Bonus', 'Profane', NULL);
insert into effect_alias (name, description) values ('Healing Lore III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Healing Lore III', 'Healing Lore', 'Equipment', 13);
insert into effect_alias (name, description) values ('Healing Lore IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Healing Lore IV', 'Healing Lore', 'Equipment', 14);
insert into effect_alias (name, description) values ('Healing Lore V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Healing Lore V', 'Healing Lore', 'Equipment', 15);
insert into effect_alias (name, description) values ('Healing Lore VI', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Healing Lore VI', 'Healing Lore', 'Equipment', 16);
insert into effect_alias (name, description) values ('Healing Lore IX', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Healing Lore IX', 'Healing Lore', 'Equipment', 19);
insert into effect_alias (name, description) values ('Healing Lore X', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Healing Lore X', 'Healing Lore', 'Equipment', 20);
insert into effect_alias (name, description) values ('Heightened Awareness', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Heightened Awareness', 'Armor Bonus', 'Insightful', NULL);
insert into effect_alias (name, description) values ('Holding On', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Holding On', 'Unconsciousness Range', 'Enhancement', 40);
insert into effect_alias (name, description) values ('Ice Lore III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Ice Lore III', 'Ice Lore', 'Equipment', 13);
insert into effect_alias (name, description) values ('Illusion Focus I', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Illusion Focus I', 'Illusion Focus', 'Equipment', 1);
insert into effect_alias (name, description) values ('Illusion Focus II', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Illusion Focus II', 'Illusion Focus', 'Equipment', 2);
insert into effect_alias (name, description) values ('Illusion Focus III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Illusion Focus III', 'Illusion Focus', 'Equipment', 3);
insert into effect_alias (name, description) values ('Illusion Focus IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Illusion Focus IV', 'Illusion Focus', 'Equipment', 4);
insert into effect_alias (name, description) values ('Illusion Focus V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Illusion Focus V', 'Illusion Focus', 'Equipment', 5);
insert into effect_alias (name, description) values ('Immunity to Fear', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Immunity to Fear', 'Fear Immunity', NULL, NULL);
insert into effect_alias (name, description) values ('Immunity to Slippery Surfaces', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Immunity to Slippery Surfaces', 'Slippery Surfaces Immunity', NULL, NULL);
insert into effect_alias (name, description) values ('Improved  False Life', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Improved  False Life', 'Hit Points', 'Enhancement', 20);
insert into effect_alias (name, description) values ('Improved False Life', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Improved False Life', 'Hit Points', 'Enhancement', 20);
insert into effect_alias (name, description) values ('Kinetic Lore VIII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Kinetic Lore VIII', 'Kinetic Lore', 'Equipment', 18);
insert into effect_alias (name, description) values ('Kinetic Lore X', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Kinetic Lore X', 'Kinetic Lore', 'Equipment', 20);
insert into effect_alias (name, description) values ('Lesser False Life', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Lesser False Life', 'Hit Points', 'Enhancement', 5);
insert into effect_alias (name, description) values ('Lifeblood of the Undead Prince', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Lifeblood of the Undead Prince', 'Negative Amplification', 'Profane', 58);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Lifeblood of the Undead Prince', 'Repair Amplification', 'Enhancement', 58);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Lifeblood of the Undead Prince', 'Healing Amplification', 'Competence', 58);
insert into effect_alias (name, description) values ('Lifeforce', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Lifeforce', 'Hit Points', 'Profane', NULL);
insert into effect_alias (name, description) values ('Lightning Guard VII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Lightning Guard VII', 'Lightning Guard', NULL, 7);
insert into effect_alias (name, description) values ('Lightning Lore III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Lightning Lore III', 'Lightning Lore', 'Equipement', 13);
insert into effect_alias (name, description) values ('Lightning Lore IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Lightning Lore IV', 'Lightning Lore', 'Equipement', 14);
insert into effect_alias (name, description) values ('Lightning Lore VI', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Lightning Lore VI', 'Lightning Lore', 'Equipement', 16);
insert into effect_alias (name, description) values ('Litany of the Dead - Ability Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead - Ability Bonus', 'Strenght', 'Profane', 1);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead - Ability Bonus', 'Dexterity', 'Profane', 1);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead - Ability Bonus', 'Constitution', 'Profane', 1);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead - Ability Bonus', 'Intelligence', 'Profane', 1);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead - Ability Bonus', 'Wisdom', 'Profane', 1);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead - Ability Bonus', 'Charisma', 'Profane', 1);
insert into effect_alias (name, description) values ('Litany of the Dead - Combat Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead - Combat Bonus', 'Accuracy', 'Profane', 1);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead - Combat Bonus', 'Deadly', 'Profane', 1);
insert into effect_alias (name, description) values ('Litany of the Dead II - Ability Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead II - Ability Bonus', 'Strenght', 'Profane', 2);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead II - Ability Bonus', 'Dexterity', 'Profane', 2);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead II - Ability Bonus', 'Constitution', 'Profane', 2);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead II - Ability Bonus', 'Intelligence', 'Profane', 2);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead II - Ability Bonus', 'Wisdom', 'Profane', 2);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead II - Ability Bonus', 'Charisma', 'Profane', 2);
insert into effect_alias (name, description) values ('Litany of the Dead II - Combat Bonus', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead II - Combat Bonus', 'Accuracy', 'Profane', 4);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Litany of the Dead II - Combat Bonus', 'Deadly', 'Profane', 4);
insert into effect_alias (name, description) values ('Magestar Absorption', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Magestar Absorption', 'Spell Absorption', NULL, 10);
insert into effect_alias (name, description) values ('Magi', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Magi', 'Wizardry', 'Enhancement', 100);
insert into effect_alias (name, description) values ('Moonlit Haunt Lore', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Moonlit Haunt Lore', 'Negative Lore', 'Equipment', 23);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Moonlit Haunt Lore', 'Force Lore', 'Equipment', 23);
insert into effect_alias (name, description) values ('Power of the Moonlit Haunt', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Moonlit Haunt', 'Nullification', 'Equipment', 157);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Moonlit Haunt', 'Impulse', 'Equipment', 157);
insert into effect_alias (name, description) values ('Necromancy Focus I', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Necromancy Focus I', 'Necromancy Focus', 'Equipment', 1);
insert into effect_alias (name, description) values ('Necromancy Focus II', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Necromancy Focus II', 'Necromancy Focus', 'Equipment', 2);
insert into effect_alias (name, description) values ('Necromancy Focus III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Necromancy Focus III', 'Necromancy Focus', 'Equipment', 3);
insert into effect_alias (name, description) values ('Necromancy Focus IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Necromancy Focus IV', 'Necromancy Focus', 'Equipment', 4);
insert into effect_alias (name, description) values ('Necromancy Focus V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Necromancy Focus V', 'Necromancy Focus', 'Equipment', 5);
insert into effect_alias (name, description) values ('Parrying', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Parrying', 'Resistance', 'Insightful', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Parrying', 'Armor Bonus', 'Insightful', NULL);
insert into effect_alias (name, description) values ('Parrying I', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Parrying I', 'Resistance', 'Insightful', 1);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Parrying I', 'Armor Bonus', 'Insightful', 1);
insert into effect_alias (name, description) values ('Parrying IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Parrying IV', 'Resistance', 'Insightful', 2);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Parrying IV', 'Armor Bonus', 'Insightful', 2);
insert into effect_alias (name, description) values ('Parrying VIII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Parrying VIII', 'Resistance', 'Insightful', 4);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Parrying VIII', 'Armor Bonus', 'Insightful', 4);
insert into effect_alias (name, description) values ('Permanent Nihil', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Permanent Nihil', 'Nullification', 'Alchemical', 30);
insert into effect_alias (name, description) values ('Pirate Cleverness', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Pirate Cleverness', 'Wizardry', 'pc', 50);
insert into effect_alias (name, description) values ('Pirate Vitality', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Pirate Vitality', 'Hit Points', 'pv', 10);
insert into effect_alias (name, description) values ('Power I', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power I', 'Wizardry', 'Enhancement', 10);
insert into effect_alias (name, description) values ('Power II', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power II', 'Wizardry', 'Enhancement', 20);
insert into effect_alias (name, description) values ('Power III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power III', 'Wizardry', 'Enhancement', 30);
insert into effect_alias (name, description) values ('Power IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power IV', 'Wizardry', 'Enhancement', 40);
insert into effect_alias (name, description) values ('Power V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power V', 'Wizardry', 'Enhancement', 50);
insert into effect_alias (name, description) values ('Power VI', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power VI', 'Wizardry', 'Enhancement', 60);
insert into effect_alias (name, description) values ('Power VII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power VII', 'Wizardry', 'Enhancement', 70);
insert into effect_alias (name, description) values ('Power VIII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power VIII', 'Wizardry', 'Enhancement', 80);
insert into effect_alias (name, description) values ('Power IX', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power IX', 'Wizardry', 'Enhancement', 90);
insert into effect_alias (name, description) values ('Power X', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power X', 'Wizardry', 'Enhancement', 100);
insert into effect_alias (name, description) values ('Sacred Ground Lore', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Sacred Ground Lore', 'Radiance Lore', 'Equipment', 22);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Sacred Ground Lore', 'Acid Lore', 'Equipment', 22);
insert into effect_alias (name, description) values ('Power of the Sacred Ground', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Sacred Ground', 'Brilliance', 'Equipment', 148);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Sacred Ground', 'Corrosion', 'Equipment', 148);
insert into effect_alias (name, description) values ('Blighted Lore', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Blighted Lore', 'Acid  Lore', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Blighted Lore', 'Void Lore', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Power of the Blight', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Blight', 'Corrosion', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Blight', 'Nullification', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Purifying Flame Lore', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Purifying Flame Lore', 'Radiance Lore', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Purifying Flame Lore', 'Fire Lore', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Power of the Flames of Purity', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Flames of Purity', 'Radiance', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Flames of Purity', 'Combustion', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Frozen Depths Lore', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Frozen Depths Lore', 'Void Lore', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Frozen Depths Lore', 'Ice Lore', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Power of the Frozen Depths', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Frozen Depths', 'Nullification', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Frozen Depths', 'Glaciation', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Frozen Storm Lore', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Frozen Storm Lore', 'Lightning Lore', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Frozen Storm Lore', 'Ice Lore', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Power of the Frozen Storm', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Frozen Storm', 'Magnetism', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Frozen Storm', 'Glaciation', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Silver Flame Lore', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Silver Flame Lore', 'Healing Lore', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Silver Flame Lore', 'Radiance Lore', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Power of the Silver Flame', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Silver Flame', 'Devotion', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Silver Flame', 'Brilliance', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Thunderstorm Lore', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Thunderstorm Lore', 'Sonic Lore', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Thunderstorm Lore', 'Lightning Lore', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Power of the Thunderstorm', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Thunderstorm', 'Resonance', 'Equipment', NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Power of the Thunderstorm', 'Magnetism', 'Equipment', NULL);
insert into effect_alias (name, description) values ('Quori Mind Shield', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Quori Mind Shield', 'Confusion Immunity', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Quori Mind Shield', 'Domination Immunity', NULL, NULL);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Quori Mind Shield', 'Chaos Absorption', 'Enhancement', 23);
insert into effect_alias (name, description) values ('Radiance Lore V', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Radiance Lore V', 'Radiance Lore', 'Equipment', 15);
insert into effect_alias (name, description) values ('Radiance Lore IX', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Radiance Lore IX', 'Radiance Lore', 'Equipment', 19);
insert into effect_alias (name, description) values ('Repair Lore III', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Repair Lore III', 'Repair Lore', 'Equipment', 13);
insert into effect_alias (name, description) values ('Repair Lore IV', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Repair Lore IV', 'Repair Lore', 'Equipment', 14);
insert into effect_alias (name, description) values ('Repair Lore VIII', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Repair Lore VIII', 'Repair Lore', 'Equipment', 18);
insert into effect_alias (name, description) values ('Riposte IX', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Riposte IX', 'Resistance', 'Insightful', 4);
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, 'Riposte IX', 'Armor Bonus', 'Insightful', 5);


insert into effect_alias (name, description) values ('', '');
insert into effect_alias_list (id, effect_name, effect, effect_type, effect_value) values (effect_alias_list_sequence.nextval, '', '', , );