insert into effect(name, effect_type) values ('Alarphon''s Staff: Spell Selection', 'clickie');
insert into effect(name, effect_type) values ('Acid Breath', 'clickie');
insert into effect(name, effect_type) values ('Aid', 'clickie');
insert into effect(name, effect_type) values ('Bestow Curse', 'clickie');
insert into effect(name, effect_type) values ('Bless', 'clickie');
insert into effect(name, effect_type) values ('Blinding Flash', 'clickie');
insert into effect(name, effect_type) values ('Blur', 'clickie');
insert into effect(name, effect_type) values ('Break Enchantment', 'clickie');
insert into effect(name, effect_type) values ('Burning Hands', 'clickie');
insert into effect(name, effect_type) values ('Call Lightning Storm', 'clickie');
insert into effect(name, effect_type) values ('Camouflage', 'clickie');
insert into effect(name, effect_type) values ('Cause Fear', 'clickie');
insert into effect(name, effect_type) values ('Chain Lightning', 'clickie');
insert into effect(name, effect_type) values ('Charm Canine', 'clickie');
insert into effect(name, effect_type) values ('Charm Person', 'clickie');
insert into effect(name, effect_type) values ('Cloudkill', 'clickie');
insert into effect(name, effect_type) values ('Cone of Cold', 'clickie');
insert into effect(name, effect_type) values ('Command Undead', 'clickie');
insert into effect(name, effect_type) values ('Control Undead', 'clickie');
insert into effect(name, effect_type) values ('Cure Critical Wounds, Mass', 'clickie');
insert into effect(name, effect_type) values ('Cure Light Wounds', 'clickie');
insert into effect(name, effect_type) values ('Cure Serious Wounds', 'clickie');
insert into effect(name, effect_type) values ('Cure Serious Wounds, Mass', 'clickie');
insert into effect(name, effect_type) values ('Cyclonic Blast', 'clickie');
insert into effect(name, effect_type) values ('Dark Discorporation', 'clickie');
insert into effect(name, effect_type) values ('Death Ward', 'clickie');
insert into effect(name, effect_type) values ('Death Ward, Mass', 'clickie');
insert into effect(name, effect_type) values ('Deep Slumber', 'clickie');
insert into effect(name, effect_type) values ('Detect Secret Doors', 'clickie');
insert into effect(name, effect_type) values ('Dimension Door', 'clickie');
insert into effect(name, effect_type) values ('Disintegrate', 'clickie');
insert into effect(name, effect_type) values ('Dismissal', 'clickie');
insert into effect(name, effect_type) values ('Dispel Madstone Effects', 'clickie');
insert into effect(name, effect_type) values ('Dispel the Grip of Strahd', 'clickie');
insert into effect(name, effect_type) values ('Displacement', 'clickie');
insert into effect(name, effect_type) values ('Doom', 'clickie');
insert into effect(name, effect_type) values ('Expeditious Retreat', 'clickie');
insert into effect(name, effect_type) values ('Fear', 'clickie');
insert into effect(name, effect_type) values ('Feather Fall', 'clickie');
insert into effect(name, effect_type) values ('Fire Shield (fire version)', 'clickie');
insert into effect(name, effect_type) values ('Fire Storm', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');
insert into effect(name, effect_type) values ('', 'clickie');

--insert into effect(name, effect_type) values ('', 'clickie');